import streamlit as st
import pandas as pd
import plotly.express as px
from utils.ui import render_global_header
from nlp.pipeline import process_complaint
from database.database import get_all_complaints

def render_home_page():
    """Render Page 1: Home View."""
    render_global_header("Home")
    
    # 1. HERO BANNER
    st.markdown(
        """
        <div class="hero-banner">
            <div class="hero-title">Welcome to <span>SENTINEL</span></div>
            <div class="hero-subtitle">Report campus issues quickly and intelligently.</div>
            <div class="hero-supporting">Your voice matters. A safer, better campus for everyone.</div>
            <div class="hero-watermark">
                Inspired by a<br>brighter tomorrow.
            </div>
        </div>
        """,
        unsafe_allow_html=True
    )
    
    # 2. MAIN SECTION: 2 BALANCED COLUMNS
    col_left, col_right = st.columns([1.15, 0.85], gap="large")
    
    with col_left:
        st.markdown(
            """
            <div style="font-size: 1.15rem; font-weight: 700; color: #17233C; margin-bottom: 0.2rem;">
                📄 Submit a Complaint
            </div>
            <div style="font-size: 0.85rem; color: #64748B; margin-bottom: 0.75rem;">
                Describe your issue in detail. Our AI will analyze and categorize it automatically.
            </div>
            """,
            unsafe_allow_html=True
        )
        
        with st.form("home_quick_complaint_form", clear_on_submit=False):
            input_text = st.text_area(
                "Complaint Description",
                height=135,
                placeholder="E.g., AC not working in my classroom...",
                label_visibility="collapsed"
            )
            
            st.markdown("<div style='font-size: 0.8rem; font-weight: 600; color: #64748B; margin-top: 0.3rem;'>Attach a file (optional)</div>", unsafe_allow_html=True)
            uploaded_file = st.file_uploader("Attach file", type=["png", "jpg", "jpeg", "pdf", "docx"], label_visibility="collapsed")
            
            submit_btn = st.form_submit_button("✨ Analyze & Submit", use_container_width=True)

        if submit_btn:
            if not input_text or not input_text.strip():
                st.warning("Please enter a complaint description before submitting.")
            else:
                with st.spinner("Processing complaint through SENTINEL NLP pipeline..."):
                    try:
                        analysis_result = process_complaint(input_text, store_in_db=True)
                        st.session_state["latest_analysis"] = analysis_result
                        st.success(f"✅ Complaint #{analysis_result['complaint_id']} submitted and saved!")
                        st.rerun()
                    except Exception as e:
                        st.error(f"Error processing complaint: {str(e)}")

    with col_right:
        st.markdown(
            """
            <div style="font-size: 1.15rem; font-weight: 700; color: #17233C; margin-bottom: 0.2rem;">
                ✨ AI Analysis
            </div>
            <div style="font-size: 0.85rem; color: #64748B; margin-bottom: 0.75rem;">
                Real-time NLP insight generated by SENTINEL models.
            </div>
            """,
            unsafe_allow_html=True
        )
        
        latest = st.session_state.get("latest_analysis")
        
        if not latest:
            st.markdown(
                """
                <div style="background: #FFFFFF; border: 1.5px dashed #CBD5E1; border-radius: 14px; padding: 3rem 1.5rem; text-align: center; color: #64748B;">
                    <div style="font-size: 2.5rem; margin-bottom: 0.4rem;">🤖</div>
                    <div style="font-weight: 700; font-size: 1rem; color: #17233C;">Submit a complaint to see AI analysis</div>
                    <div style="font-size: 0.82rem; color: #64748B; margin-top: 0.3rem;">Category, urgency, location, and summary will appear here.</div>
                </div>
                """,
                unsafe_allow_html=True
            )
        else:
            urgency = latest["urgency"]
            urg_class = {
                "Critical": "badge-critical",
                "High": "badge-high",
                "Medium": "badge-medium",
                "Low": "badge-low"
            }.get(urgency, "badge-low")
            
            dup = latest.get("duplicate", {})
            dup_str = f"Duplicate found (#{dup.get('matched_id')})" if dup.get("is_duplicate") else "No similar complaint found"
            
            st.markdown(
                f"""
                <div style="background: #FFFFFF; border: 1px solid #E2E8F0; border-radius: 14px; padding: 1.25rem;">
                    <div style="display: flex; justify-content: space-between; align-items: center; margin-bottom: 0.75rem;">
                        <span style="font-size: 0.85rem; font-weight: 600; color: #64748B;">Category</span>
                        <span style="background-color: #FFF3ED; color: #F15A24; font-weight: 700; font-size: 0.85rem; padding: 0.25rem 0.65rem; border-radius: 6px;">{latest['category']}</span>
                    </div>
                    <div style="display: flex; justify-content: space-between; align-items: center; margin-bottom: 0.75rem;">
                        <span style="font-size: 0.85rem; font-weight: 600; color: #64748B;">Priority</span>
                        <span class="badge {urg_class}">{urgency}</span>
                    </div>
                    <div style="display: flex; justify-content: space-between; align-items: center; margin-bottom: 0.75rem;">
                        <span style="font-size: 0.85rem; font-weight: 600; color: #64748B;">Location</span>
                        <span style="background-color: #EFF6FF; color: #2563EB; font-weight: 600; font-size: 0.85rem; padding: 0.25rem 0.65rem; border-radius: 6px;">{latest['entities']['location']}</span>
                    </div>
                    <div style="margin-top: 0.8rem; padding-top: 0.8rem; border-top: 1px solid #F1F5F9;">
                        <div style="font-size: 0.75rem; font-weight: 700; color: #64748B; margin-bottom: 0.25rem; uppercase;">SUMMARY</div>
                        <div style="font-size: 0.88rem; color: #17233C; line-height: 1.4;">{latest['summary']}</div>
                    </div>
                    <div style="margin-top: 0.8rem; padding-top: 0.8rem; border-top: 1px solid #F1F5F9; font-size: 0.8rem; color: #64748B;">
                        <strong>Duplicate Status:</strong> {dup_str}
                    </div>
                </div>
                """,
                unsafe_allow_html=True
            )

    st.markdown("<div style='margin-bottom: 1.75rem;'></div>", unsafe_allow_html=True)
    
    # 3. 4 KPI STAT CARDS (REAL SQLITE DB QUERIES)
    all_complaints = get_all_complaints()
    df = pd.DataFrame(all_complaints) if all_complaints else pd.DataFrame()
    
    total_count = len(df)
    high_priority_count = len(df[df['urgency'].isin(['High', 'Critical'])]) if not df.empty else 0
    resolved_count = len(df[df['status'] == 'Resolved']) if not df.empty else 0
    duplicates_count = len(df[df['is_duplicate'] == 1]) if not df.empty else 0

    col_s1, col_s2, col_s3, col_s4 = st.columns(4)
    
    with col_s1:
        st.markdown(
            f"""
            <div class="stat-card">
                <div class="stat-icon-box stat-icon-orange">📄</div>
                <div class="stat-content">
                    <div class="stat-label">Total Complaints</div>
                    <div class="stat-value">{total_count}</div>
                </div>
            </div>
            """,
            unsafe_allow_html=True
        )
        
    with col_s2:
        st.markdown(
            f"""
            <div class="stat-card">
                <div class="stat-icon-box stat-icon-red">⚠️</div>
                <div class="stat-content">
                    <div class="stat-label">High Priority</div>
                    <div class="stat-value">{high_priority_count}</div>
                </div>
            </div>
            """,
            unsafe_allow_html=True
        )

    with col_s3:
        st.markdown(
            f"""
            <div class="stat-card">
                <div class="stat-icon-box stat-icon-green">✅</div>
                <div class="stat-content">
                    <div class="stat-label">Resolved</div>
                    <div class="stat-value">{resolved_count}</div>
                </div>
            </div>
            """,
            unsafe_allow_html=True
        )

    with col_s4:
        st.markdown(
            f"""
            <div class="stat-card">
                <div class="stat-icon-box stat-icon-blue">👥</div>
                <div class="stat-content">
                    <div class="stat-label">Duplicates</div>
                    <div class="stat-value">{duplicates_count}</div>
                </div>
            </div>
            """,
            unsafe_allow_html=True
        )

    st.markdown("<div style='margin-bottom: 1.75rem;'></div>", unsafe_allow_html=True)
    
    # 4. RECENT COMPLAINTS & STATUS DONUT CHART GRID
    grid_left, grid_right = st.columns([1.25, 0.75], gap="large")
    
    with grid_left:
        st.markdown("<div style='font-size: 1.1rem; font-weight: 700; color: #17233C; margin-bottom: 0.75rem;'>Recent Complaints</div>", unsafe_allow_html=True)
        
        if df.empty:
            st.info("No complaints submitted yet.")
        else:
            recent_df = df.head(5)[['id', 'complaint_text', 'category', 'urgency', 'status', 'created_at']].copy()
            recent_df.columns = ['#', 'Complaint', 'Category', 'Priority', 'Status', 'Date']
            recent_df['Date'] = recent_df['Date'].astype(str).str.slice(0, 10)
            
            st.dataframe(
                recent_df,
                use_container_width=True,
                hide_index=True,
                column_config={
                    "#": st.column_config.NumberColumn("ID", width="small"),
                    "Complaint": st.column_config.TextColumn("Complaint", width="large"),
                    "Category": st.column_config.TextColumn("Category", width="medium"),
                    "Priority": st.column_config.TextColumn("Priority", width="small"),
                    "Status": st.column_config.TextColumn("Status", width="small"),
                    "Date": st.column_config.TextColumn("Date", width="small"),
                }
            )

    with grid_right:
        st.markdown("<div style='font-size: 1.1rem; font-weight: 700; color: #17233C; margin-bottom: 0.75rem;'>Status Overview</div>", unsafe_allow_html=True)
        
        if df.empty:
            st.info("No data for donut chart yet.")
        else:
            status_counts = df['status'].value_counts().reset_index()
            status_counts.columns = ['Status', 'Count']
            
            fig = px.pie(
                status_counts,
                values='Count',
                names='Status',
                hole=0.55,
                color_discrete_sequence=['#16A34A', '#3B82F6', '#F59E0B', '#EF4444']
            )
            fig.update_layout(
                margin=dict(t=0, b=0, l=0, r=0),
                height=220,
                showlegend=True,
                legend=dict(orientation="h", yanchor="bottom", y=-0.25, xanchor="center", x=0.5)
            )
            st.plotly_chart(fig, use_container_width=True, config={"displayModeBar": False})

